### ISSUE TITLE
ini's on server not findable

### ISSUE THREAD

**Issue by HolgerPollyNet** [NOA-ReACT/PollyXT-SCC-Pipelines#1]
We have installed the pipelines on our server. 

However, when I type:
pollyxt_pipelines locations-path
the result is:
/etc/pollyxt_pipelines/locations.ini
/MAINHOME/.config/pollyxt_pipelines/locations.ini
However, non of the directory exists.
Finally, we found the locations.ini at 
/MAINHOME/scc_env/lib/python3.8/site-packages/pollyxt_pipelines

Same problem occurs for the "pollyxt_pipelines.ini".

But so far, we could not find it....
Can you provide advise or send an example ini for accessing the SCC?

**Comment by thgeorgiou** [comment]
Hello! You can create these directories/files. The one you found inside `site-packages/pollyxt_pipelines` is the "default" one, which is merged at runtime with the user's `location.ini`.

Thus, you can either create `/etc/pollyxt_pipelines/locations.ini` which applies for all users in that machine or `/MAINHOME/.config/pollyxt_pipelines/locations.ini` which applies only for that specific logged in user.

**Comment by HolgerPollyNet** [comment]
Okay understood! Thanks!

What about the pollyxt_pipelines.ini for scc_access. Could you provide a template (maybe via email)?

**Comment by thgeorgiou** [comment]
After running the following command, you will be prompted for your credentials and `pollyxt_pipelines.ini` will be generated for you:

```sh
pollyxt_pipelines login
```

**Comment by thgeorgiou** [comment]
I believe version 1.6.4 fixes all (most?) of the configuration-related issues, if something else arises please create another issue!
