### ISSUE TITLE
Depol calibration

### ISSUE THREAD

**Issue by HolgerPollyNet** [NOA-ReACT/PollyXT-SCC-Pipelines#17]
Hi, as for several polly systems the depol calibration times are different:

Is there a way to adjust the depol calibration times? I.e. not fixed to: 

    02:31 to 02:41
    17:31 to 17:41
    21:31 to 21:41

Or is there a way we, can support this?

**Comment by HolgerPollyNet** [comment]
[Update pollyxt.py](https://github.com/HolgerPollyNet/PollyXT-SCC-Pipelines/commit/b96fab93de1de5f56c9ac3f73c7c75090bf72224)

line 167: "...!= 0", the 0 should be a variable (e.g. depol_angle_regular_measurement) which is read from locations.ini. for some polly systems it is a different angle.
E.g: 
Arielle: 19.98755
TROPOS: 999
NOA: 000000 
1v2: 0.0000
tau: 350
tjk: 0000

Furthermore, it is important to skip the first and last measurement of the period when the depol_cal_angle is not regular. Because the filter wheel is storing its position only once during the 30 seconds measurement. So be on the save side, you should skip the first and last of the +45 period, and the first and last of the - 45 period. 

Example: PollyXT_FMI:

index: 
420	421	422	423	424	425	426	427	428	429	430	431	432	433	434	435	436	437	438	439	440	441	442	443
Depol cal angle:
0.0	151	151	151	151	151	151	151	151	151	151	241	241	241	241	241	241	241	241	241	241	255	0.0	0.0
--> use for +45: 422--429 and for -45 432--439

Thank you very much,this will help the improve the Polly SCC performance a lot!

**Comment by thgeorgiou** [comment]
Hello Holger, sorry for my late response, I was on my summer break!

This is great information, we were trying to make depol. use the `depol_cal_angle` variable but I didn't know about the measurement cycles. This is probably what caused some issues we were seeing.

I will definitely implement this and let you know.

**Comment by thgeorgiou** [comment]
@HolgerPollyNet Hello Holger, hope everything is well.

In the SCC file, should we include all `raw_signal` points that correspond to the indices you described or some statistic of them (eg. one point only with the average)?

Thank you for your insight!

CC @mtsichla

**Comment by HolgerPollyNet** [comment]
yes, please include all raw signal points, the SCC needs this for its own statistics.

**Comment by ulysses78** [comment]
Hi @thgeorgiou ,
can you tell when this feature (commit 8f818ec7f9df5f05b4488b139dbfada94622679e) will be implemented in a new pypi version of pollyxt_pipelines? It would be great if we can finally set our depol-angles (```depol_calibration_zero_state```) in the locations.ini config-file :-)

Best regards,
Andi

**Comment by thgeorgiou** [comment]
Hello @ulysses78!

We have been doing some testing with Maria (@mtsichla) to check whether it's working correctly, but I guess there is no reason you can't try it too. I will push the new version tomorrow, after I write some documentation for the new behaviour!

**Comment by thgeorgiou** [comment]
Small update from my side. We asked Giuseppe D'Amico for some info and now we think something is wrong with this code. In addition, our depol. calibration doesn't change at all which is suspicious. We will continue working on this before making a new release.

Nonetheless, I am uploading a wheel file here in case anyone wants to try the code (@ulysses78). You can download the file, extract the wheel (.whl), put it in a folder and install it like:

```
pip install ./pollyxt_pipelines-1.11.7-py3-none-any.whl
```
Cheers!

[pollyxt_pipelines-1.11.7-py3-none-any.whl.zip](https://github.com/NOA-ReACT/PollyXT-SCC-Pipelines/files/9787017/pollyxt_pipelines-1.11.7-py3-none-any.whl.zip)

**Comment by thgeorgiou** [comment]
Hello all,

we have pushed a new build to PyPI (1.12.0) that includes the fixes discussed here. I hope it improves performance for you, please let me know if you have any feedback!

For reference, I wrote some details about how calibration files are generated in the documentation [here](https://noa-react.github.io/PollyXT-SCC-Pipelines/convert-scc.html#calibration).

Take care!
