### ISSUE TITLE
depol calibration

### ISSUE THREAD

**Issue by HolgerPollyNet** [NOA-ReACT/PollyXT-SCC-Pipelines#3]
Hi,

I realized that I cannot specify a configuration ID for the depolarization_configuration in analogy to "System ID (daytime_configuration, nighttime_configuration)".

But only if this is possible, depol calibrations can be uploaded.

Furthermore, is the current depol calibration period still based on fix times or are the angles already considered?

Thanks for the great work, looking forward to the updates 😉

**Comment by thgeorgiou** [comment]
Hello!

Yes I wanted to implement this, I should consult Anna on the gritty details because I am not sure how it should work.
Generally, I was thinking of adding a new `create-scc-calibration` command since the current way is a bit unreliable. This way we can also add Mattis' code for verifying that the calibration makes sense.

**Comment by HolgerPollyNet** [comment]
Hi @thgeorgiou , thanks for the new release including depol calibration. is not the system ID for the calibrating system required as well? The depol calibration files should be uploaded using a different system number, which should be indicated in the locations.ini, right?

**Comment by HolgerPollyNet** [comment]
Again me @thgeorgiou , in case you have different systems also the depol calibration times are different. In the polly netcdf there is a variable stored depol_cal_angle. This one should be read to know when calibration is performed. Can you do so? For most of the systems the standard depol_cal_value is 0. Meaning all time slots for which this angle is nonzero, are calibration times....

**Comment by thgeorgiou** [comment]
Hello @HolgerPollyNet,

Indeed, I will add a setting in `locations.ini` for setting the system ID for uploading calibration files and possibly a different command. I am working on it right now. I will also remove the fixed times in favor of reading `depol_cal_angle`, I will keep you posted.

**Comment by thgeorgiou** [comment]
Implemented in v1.9.0!
